version: 1
disable_existing_loggers: False
formatters:
    standard:
        format: "[%(asctime)s][%(name)s][%(levelname)s] >>> %(message)s"
    short:
        format: "[%(name)s][%(levelname)s] >>> %(message)s"

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: standard

    file:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        encoding: utf8

loggers:
    "":
        level: INFO
        handlers: [console, file]
        propagate: no